CREATE TABLE User (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Password (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Username VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Website VARCHAR(255),
  Notes TEXT,
  Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (User_ID) REFERENCES User(ID)
);
